# Generated by Django 5.1.4 on 2024-12-25 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory_manager_app.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wholesaler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesaler', to='inventory_manager_app.wholesaler'),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wholesaler', to=settings.AUTH_USER_MODEL),
        ),
    ]
