# Generated by Django 5.1.4 on 2024-12-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager_app', '0006_alter_productimage_product_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
