# Generated by Django 5.1.4 on 2025-01-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager_app', '0012_product_color_variant_product_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='color_images'),
        ),
    ]
